"""Python-only judge impact report for Opportunity Radar.

This module exports a plain-text report instead of HTML. It keeps the project
unambiguously Python-only while still giving judges a polished snapshot of the
system's impact.
"""

import datetime
import os

import access
import demand
import matcher
import sender
import stats


def open_opportunities(opportunities):
    """Return non-expired opportunities."""
    result = []

    for opportunity in opportunities:
        if matcher.days_until(opportunity.deadline) >= 0:
            result.append(opportunity)

    return result


def metric_lines(opportunities, searches_path):
    """Return headline metric lines for the report."""
    open_items = open_opportunities(opportunities)
    ratio = stats.free_vs_paid_ratio(opportunities)
    beginner_count = 0

    for opportunity in open_items:
        if opportunity.beginner_friendly:
            beginner_count = beginner_count + 1

    return [
        "Open opportunities: " + str(len(open_items)),
        "Free opportunity share: " + str(ratio["free_pct"]) + "%",
        "Beginner-friendly opportunities: " + str(beginner_count),
        "Anonymous demand signals: " + str(demand.total_searches(searches_path)),
    ]


def demand_gap_lines(opportunities, searches_path):
    """Return demand-vs-supply lines for senders."""
    rows = sender.build_gap_rows(opportunities, searches_path, limit=8)

    if len(rows) == 0:
        rows = sender.build_supply_thin_rows(opportunities, limit=8)

    if len(rows) == 0:
        return ["No demand or supply data yet."]

    lines = []
    for row in rows:
        gap = row["gap_score"]
        if gap > 0:
            gap_text = "+" + str(gap)
        else:
            gap_text = str(gap)

        lines.append(
            row["interest"]
            + " | demand "
            + str(row["demand"])
            + " | supply "
            + str(row["supply"])
            + " | gap "
            + gap_text
            + " | "
            + sender.priority_label(row)
        )

    return lines


def starting_line_lines(opportunities, student):
    """Return starting-line simulation lines."""
    if student is None:
        return ["No student profile loaded."]

    report = access.build_access_report(opportunities, student)
    lines = []

    for summary in report["personas"]:
        lines.append(
            summary["label"]
            + ": before Radar "
            + format(summary["expected_before"], ".1f")
            + " of "
            + str(summary["after_radar"])
            + " | after Radar "
            + str(summary["after_radar"])
            + " | recovered +"
            + format(summary["recovered"], ".1f")
        )

    return lines


def top_match_lines(opportunities, student, limit=5):
    """Return the student's top matched opportunities."""
    if student is None:
        return ["No student profile loaded."]

    results = matcher.rank_opportunities(opportunities, student)[:limit]
    if len(results) == 0:
        return ["No eligible matches for this profile."]

    lines = []
    for index, result in enumerate(results):
        opportunity = result["opportunity"]
        lines.append(
            str(index + 1)
            + ". "
            + opportunity.title
            + " | "
            + opportunity.organizer
            + " | deadline "
            + opportunity.deadline
            + " | score "
            + format(result["score"], ".3f")
        )

    return lines


def section(title, lines):
    """Return a formatted report section."""
    output = []
    output.append("")
    output.append(title)
    output.append("-" * len(title))
    for line in lines:
        output.append(line)
    return output


def build_report_text(opportunities, searches_path, student=None):
    """Build the full plain-text judge impact report."""
    generated = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines.append("=" * 62)
    lines.append("OPPORTUNITY RADAR - JUDGE IMPACT REPORT")
    lines.append("=" * 62)
    lines.append("Generated: " + generated)
    lines.append("")
    lines.append("The gap is not talent. The gap is who hears in time.")
    lines.append("This report is generated by Python from the live JSON data.")

    lines.extend(section("Headline Metrics", metric_lines(opportunities, searches_path)))
    lines.extend(section("Sender Demand Radar", demand_gap_lines(opportunities, searches_path)))
    lines.extend(section("Invisible Starting-Line Simulation", starting_line_lines(opportunities, student)))
    lines.extend(section("Top Student Matches", top_match_lines(opportunities, student)))

    lines.append("")
    lines.append("Python-only evidence:")
    lines.append("- Standard library only")
    lines.append("- JSON File I/O")
    lines.append("- OOP model classes")
    lines.append("- Recursive interest taxonomy")
    lines.append("- Transparent scoring")
    lines.append("- Crash-resistant validation and loaders")

    return "\n".join(lines) + "\n"


def save_report(path, opportunities, searches_path, student=None):
    """Write the impact report text file and return its absolute path."""
    absolute_path = os.path.abspath(path)
    folder = os.path.dirname(absolute_path)
    if folder != "" and not os.path.exists(folder):
        os.makedirs(folder)

    temp_path = absolute_path + ".tmp"
    content = build_report_text(opportunities, searches_path, student)

    try:
        with open(temp_path, "w", encoding="utf-8") as file_handle:
            file_handle.write(content)
        os.replace(temp_path, absolute_path)
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)

    return absolute_path
